version: '3'

services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - node-network
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - app
    entrypoint: /bin/bash -c "dockerize -wait tcp://app:3000 -timeout 20s && nginx -g 'daemon off;'"
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db
    entrypoint: bash -c "dockerize -wait tcp://db:3306 -timeout 20s && chmod 777 -R . && npm install . && node index.js"
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./script-inicial.sql:/docker-entrypoint-initdb.d/script-inicial.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      #- MYSQL_USER=root      
    networks:
      - node-network

networks:
  node-network:
    driver: bridge

   